[platformio]
default_envs = T-Deck
boards_dir = boards

[env:T-Deck]
platform = espressif32@6.3.0
board = T-Deck
framework = arduino

upload_speed = 921600
monitor_speed = 115200

lib_deps =
    https://github.com/Lora-net/sx126x_driver.git#v2.3.2
    lewisxhe/SensorLib

build_flags =
    -DBOARD_HAS_PSRAM=1
    -DCORE_DEBUG_LEVEL=1
    -DARDUINO_USB_CDC_ON_BOOT=1
